packages:
  - "apps/*"
  - "services/go/*"
  - "services/cs/*"
  - "services/rust/*"
  - "services/ts/*"
  - "services/py/*"
  - "packages/*"
  - "packages/ts/*"
  - "packages/cs/*"
  - "packages/go/*"
  - "packages/py/*"
  - "packages/rust/*"
