FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["portfolio-service.csproj", "./"]
RUN dotnet restore "portfolio-service.csproj"

COPY . .
RUN dotnet build "portfolio-service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "portfolio-service.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 3200

ENTRYPOINT ["dotnet", "portfolio-service.dll"]

